 #
 # This class is automatically generated by ncg. DO NOT EDIT THIS FILE.
 # This class includes values of some nesC constants from
 # ../SensorNode/SensorNode.h.
 #/

class Constants:
    DEFAULT_INTERVAL = 256
    NREADINGS = 2
    AM_SENSORNODE = 147

